create table
    insights (
                        id bigint generated by default as identity not null,
                        slug text not null,
                        constraint insights_pkey primary key (id)
);
