create table
    roi_volumes (
                           id bigint generated by default as identity not null,
                           created_at timestamp with time zone not null default now(),
                           updated_at timestamp with time zone null default now(),
                           nifti_file_id uuid not null,
                           label text not null,
                           volume double precision not null,
                           constraint roi_volumes_pkey primary key (id),
                           constraint roi_volumes_nifti_file_id_fkey foreign key (nifti_file_id) references nifti_files (id) on update cascade on delete cascade
);

create unique index if not exists roi_volumes_nifti_file_id_label_idx on roi_volumes using btree (nifti_file_id, label);
