-- --------------------------------------------------------------
--                                                            --
--                      public.usermeta                       --
--                                                            --
-- --------------------------------------------------------------

drop function if exists set_user_meta;

drop table if exists usermeta;

-- --------------------------------------------------------------

-- Create a table
create table usermeta (
  id bigint generated by default as identity primary key,
  user_id uuid references users(id) on delete cascade not null,
  meta_key varchar(255) not null,
  meta_value text,
  unique(user_id, meta_key)
);

-- Add table indexing
create index usermeta_user_id_idx on usermeta (user_id);
create index usermeta_meta_key_idx on usermeta (meta_key);

-- Secure the table
alter table usermeta enable row level security;

-- Add row-level security
create policy "Public access for all users" on usermeta for select to authenticated, anon using ( true );
create policy "User can insert their own usermeta" on usermeta for insert to authenticated with check ( (select auth.uid()) = user_id );
create policy "User can update their own usermeta" on usermeta for update to authenticated using ( (select auth.uid()) = user_id );
create policy "User can delete their own usermeta" on usermeta for delete to authenticated using ( (select auth.uid()) = user_id );

-- --------------------------------------------------------------

create or replace function set_user_meta(p_user_id uuid, p_meta_key text, p_meta_value text = null)
returns setof usermeta
security definer set search_path = public
    as $$
begin
    if exists (select 1 from usermeta where user_id = p_user_id and meta_key = p_meta_key) then
update usermeta set meta_value = p_meta_value, updated_at = now() where user_id = p_user_id and meta_key = p_meta_key;
else
insert into usermeta(user_id, meta_key, meta_value) values(p_user_id, p_meta_key, p_meta_value);
end if;
return QUERY SELECT * FROM usermeta WHERE user_id = p_user_id AND meta_key = p_meta_key;
end;
$$ language plpgsql;
