create table
    user_insights (
                             id bigint generated by default as identity not null,
                             insight_id bigint not null,
                             user_id uuid null,
                             created_at timestamp with time zone null default now(),
                             updated_at timestamp with time zone null default now(),
                             archived_at timestamp with time zone null,
                             nifti_file_id uuid null,
                             constraint user_insights_pkey primary key (id),
                             constraint user_insights_insight_id_fkey foreign key (insight_id) references insights (id) on update cascade on delete cascade,
                             constraint user_insights_nifti_file_id_fkey foreign key (nifti_file_id) references nifti_files (id) on update cascade on delete cascade,
                             constraint user_insights_user_id_fkey foreign key (user_id) references users (id) on update cascade on delete cascade
);

CREATE UNIQUE INDEX user_insights_insight_id_user_id_nifti_file_id_idx ON public.user_insights USING btree (insight_id, user_id, nifti_file_id);
