create table
    user_insight_outputs (
                                    id bigint generated by default as identity not null,
                                    user_insight_id bigint null,
                                    created_at timestamp with time zone not null default now(),
                                    name text not null,
                                    value text not null,
                                    type text null,
                                    constraint user_insight_outputs_pkey primary key (id),
                                    constraint user_insight_outputs_user_insight_id_fkey foreign key (user_insight_id) references user_insights (id) on update cascade on delete cascade
);

CREATE UNIQUE INDEX user_insight_outputs_user_insight_id_name_idx ON public.user_insight_outputs USING btree (user_insight_id, name);
